clusterServerCfg:
  masterURL: https://tke-platform-api
  kubeConfig: /app/conf/tke-platform-config.yaml
  enableEvent: false
coreDnsCfg:
  corefilePath: /etc/coredns/Corefile
  zonesDir: /etc/coredns/zones
  wildcardDomainSuffix:
  interval: 2s
  jitter: 1s
