apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cluster-coredns-controller
  namespace: tke
spec:
  selector:
    matchLabels:
      name: cluster-coredns-controller
  template:
    metadata:
      labels:
        name: cluster-coredns-controller
    spec:
      containers:
      - name: cluster-coredns-controller
        image: REPLACE_IMAGE
        imagePullPolicy: IfNotPresent
        volumeMounts:
        - name: coredns-config-dir
          mountPath: /etc/coredns
        - name: cluster-coredns-controller-config
          mountPath: /cluster-coredns-controller/examples
          readOnly: true
      volumes:
      - name: coredns-config-dir
        hostPath:
          path: /etc/coredns
      - name: cluster-coredns-controller-config
        configMap:
          name: cluster-coredns-controller
