apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: cluster-coredns-controller
rules:
  - apiGroups: ["platform.tkestack.io"]
    resources: ["clusters"]
    verbs: ["create", "get", "watch", "list", "delete", "patch", "update"]