apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cluster-coredns-controller
subjects:
  - kind: ServiceAccount
    name: default # Name is case sensitive
    namespace: tke
roleRef:
  kind: ClusterRole #this must be Role or ClusterRole
  name: cluster-coredns-controller
  apiGroup: rbac.authorization.k8s.io